#!/usr/bin/env bash

#rofi_command="rofi -theme $HOME/.config/rofi/exit/powermenu.rasi"
uptime=$(uptime -p | sed -e 's/up //g')

# Buttons

layout=$(grep BUTTON "$HOME"/.config/rofi/exit/powermenu-2.rasi | cut -d'=' -f2 | tr -d '[:blank:],*/')
if [[ "$layout" == "TRUE" ]]; then
    shutdown=""
    reboot=""
    lock=""
    suspend="󱋑"
    logout=""

else
    shutdown=" Shutdown"
    reboot=" Restart"
    lock=" Lockscreen"
    suspend="󱋑 Suspend"
    logout=" logout"
fi
ddir="$HOME/.config/rofi/exit"

# Ask for confirmation
rdialog () {
    rofi -dmenu\
        -i\
        -no-fixed-num-lines\
        -p "Are You Sure? : "\
        -theme "$ddir/confirm.rasi"
}

# Display Help
show_msg() {
    rofi -theme "$ddir/ask.rasi" -e "Options : yes / no / y / n"
}

# Variable passed to rofi
options="$lock\n$suspend\n$logout\n$reboot\n$shutdown"

chosen="$(echo -e "$options" | rofi -dmenu -p "$uptime" -i -theme "$HOME/.config/rofi/exit/powermenu-2.rasi")"
case $chosen in
    "$shutdown")
        ans=$(rdialog &)
        if [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]]; then
            systemctl poweroff
        elif [[ $ans == "no" ]] || [[ $ans == "NO" ]] || [[ $ans == "n" ]]; then
            exit
        else
            show_msg
        fi
        ;;
    "$reboot")
        ans=$(rdialog &)
        if [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]]; then
            systemctl reboot
        elif [[ $ans == "no" ]] || [[ $ans == "NO" ]] || [[ $ans == "n" ]]; then
            exit
        else
            show_msg
        fi
        ;;
    "$lock")
        ~/.config/hypr/scripts/lock        ;;
    "$suspend")
        ans=$(rdialog &)
        if [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]]; then
            systemctl suspend
        elif [[ $ans == "no" ]] || [[ $ans == "NO" ]] || [[ $ans == "n" ]]; then
            exit
        else
            show_msg
        fi
        ;;
    "$logout")
        ans=$(rdialog &)
        if [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]]; then
            pkill -KILL -u "$USER"
        elif [[ $ans == "no" ]] || [[ $ans == "NO" ]] || [[ $ans == "n" ]]; then
            exit
        else
            show_msg
        fi
        ;;
esac
