#!/bin/bash

# config rofi
rofi_command="rofi -theme $HOME/.config/rofi/recording/record.rasi"

icon="$HOME/.config/mako/icons/screenshot.svg"

# Buttons
layout=$(grep BUTTON "$HOME"/.config/rofi/recording/record.rasi| cut -d'=' -f2 | tr -d '[:blank:],*/')
if [[ "$layout" == "TRUE" ]]; then
    video_audio=""
    video=""
    area=""
    stop=""
else
    video_audio=" Recording video & audio"
    video=" Recording video only"
    area=" Record selected area"
    stop=" Stop recording"
fi

# Notify and view screenshot
show_notification () {
    notify-send -h string:x-canonical-private-synchronous:hypr-cfg -u low -i "$icon" "Recording Saved..."
}

# Record audio and video
record_video_audio() {
    wf-recorder --audio=alsa_output.pci-0000_00_1b.0.analog-stereo.monitor -f "$(xdg-user-dir VIDEOS)/$(date +'%H:%M:%S_%d-%m-%Y.mp4')"
    show_notification
}

# Record video only
record_video() {
    wf-recorder -f "$(xdg-user-dir VIDEOS)/$(date +'%H:%M:%S_%d-%m-%Y.mp4')"
    show_notification
}

# Record video only
record_selected_video() {
    wf-recorder -g "$(slurp)" -f "$(xdg-user-dir VIDEOS)/$(date +'%H:%M:%S_%d-%m-%Y.mp4')"
    show_notification
}

# Use rofi to offer options for stopping the recording
options="$video_audio\n$video\n$area\n$stop"

chosen="$(echo -e "$options" | $rofi_command -p '==Screen recording menu==' -dmenu)"
case $chosen in
    "$video_audio")
        record_video_audio
        ;;
    "$video")
        record_video
        ;;
    "$area")
        record_selected_video
        ;;
    "$stop")
        killall -s SIGINT wf-recorder
        ;;
esac
