#!/bin/bash

swayidle -w timeout 300 "$HOME/.config/hypr/scripts/lock && playerctl stop" \
            timeout 600 "hyprctl dispatch dpms off" \
            resume "hyprctl dispatch dpms on" \
            timeout 900 "systemctl suspend" \
            before-sleep "$HOME/.config/hypr/scripts/lock && playerctl stop" &
